#%RAML 1.0 Trait

description: to create headers

headers:
  client-id:
    type: string
    description: to generate client id for the systme call
    required: true
  client-secret:
    type: string
    description: to generate client secret for the system call
    required: true